---
controller_hosts:
  - name: localhost
    inventory: Cac-Demo-Inventory
    variables:
      # some_var: some_val
      ansible_connection: local
  - name: node-01.example.com
    inventory: Cac-Demo-Inventory
    variables:
      # some_var: some_val
      # ansible_connection: local
...
