---
controller_settings_individuale:
  - name: AWX_TASK_ENV
    value: {'GIT_SSL_NO_VERIFY': 'True'}

  ################### LDAP ############################
  - name: AUTH_LDAP_SERVER_URI
    value: "ldap://192.168.57.137:389"

  - name: AUTH_LDAP_BIND_DN
    value: "CN=ansible_bind,CN=users,DC=example,DC=com"

  # - name: AUTH_LDAP_BIND_PASSWORD
  #   value: "yoursecretbindpassword"

  - name: AUTH_LDAP_START_TLS
    value: false

  # - name: AUTH_LDAP_USER_DN_TEMPLATE
  #   value: "uid=%(user)s,ou=Users,dc=example,dc=com"

  - name: AUTH_LDAP_GROUP_TYPE
    value: "MemberDNGroupType"

  - name: AUTH_LDAP_USER_SEARCH
    value: "['DC=example,DC=com', 'SCOPE_SUBTREE', '(sAMAccountName=%(user)s)']"

  - name: AUTH_LDAP_GROUP_SEARCH
    value: "['DC=example,DC=com', 'SCOPE_SUBTREE', '(objectClass=group)']"

  - name: AUTH_LDAP_USER_ATTR_MAP
    value: '{"first_name": "givenName","last_name": "sn","email": "mail"}'


  - name: AUTH_LDAP_ORGANIZATION_MAP
    value: '{
            "XYZCorp-CaC": {
              "users": true,
              "admins": "CN=ansible_admins,OU=AAP,DC=example,DC=com",
              "remove_users": false,
              "remove_admins": false
            },
            "Network-Ops": {
              "users": true,
              "admins": "CN=network_admins,OU=AAP,DC=example,DC=com",
              "remove_users": false,
              "remove_admins": false
            }
          }'

  # This maps all users to satellite-qe team and we need to add this team to all resources we create for them
  # that way users can access the things that their team has permissions for

  - name: AUTH_LDAP_TEAM_MAP
    value: '{
            "cac-admins": {
              "users": "cn=ansible_admins,ou=AAP,dc=example,dc=com",
              "remove": true,
              "organization": "XYZCorp-CaC"
            },
            "cac-operators": {
              "users": "cn=ansible_operators,ou=AAP,dc=example,dc=com",
              "remove": true,
              "organization": "XYZCorp-CaC"
            },
            "network-admins": {
              "users": "cn=network_admins,ou=AAP,dc=example,dc=com",
              "remove": true,
              "organization": "Network-Ops"
            },
            "network-operators": {
              "users": "cn=network_operators,ou=AAP,dc=example,dc=com",
              "remove": true,
              "organization": "Network-Ops"
            }
          }'
  # - name: AUTH_LDAP_REQUIRE_GROUP
  #   value: "cn=satellite-qe,ou=adhoc,ou=managedGroups,dc=example,dc=com"
  # # Next name helps fetch Email addr and name from LDAP and save it in tower user.
  # - name: AUTH_LDAP_USER_ATTR_MAP
  #   value: '{"first_name": "displayName","last_name": "sn","email": "examplePrimaryMail"}'
  # # Next name helps each sat-qe-infra group to become superuser in tower as soon as they login
  # - name: AUTH_LDAP_USER_FLAGS_BY_GROUP
  #   value: "{u'is_superuser': ['cn=sat-qe-infra,ou=adhoc,ou=managedGroups,dc=example,dc=com']}"
  # # This maps all users to satellite-qe org and makes sure they are not part of satlab-admin
  # - name: AUTH_LDAP_ORGANIZATION_MAP
  #   value: '{
  #    "Satellite": {
  #     "users": true
  #    }
  #   }'
  # # This maps all users to satellite-qe team and we need to add this team to all resources we create for them
  # # that way users can access the things that their team has permissions for
  # - name: AUTH_LDAP_TEAM_MAP
  #   value: '{
  #    "satellite-qe": {
  #     "organization": "Satellite",
  #     "users": true
  #    },
  #    "satlab-admin": {
  #     "organization": "Satellite",
  #     "users": "cn=sat-qe-infra,ou=adhoc,ou=managedGroups,dc=example,dc=com"
  #    }
  #   }'




  # - name: AUTH_LDAP_1_USER_SEARCH
  #   value: '[ "OU=AAP,DC=example,DC=com","SCOPE_SUBTREE", "(sAMAccountName=%(user)s) ]"'
  # - name: AUTH_LDAP_1_SERVER_URI
  #   value: "ldap://ldap2.example.com"
  # - name: AUTH_LDAP_1_USER_DN_TEMPLATE
  #   value: "uid=%(user)s,ou=Users,dc=example,dc=com"
  # - name: AUTH_LDAP_1_GROUP_SEARCH
  #   value: "['dc=example,dc=com', 'SCOPE_SUBTREE', '(objectClass=person)']"
  # - name: AUTH_LDAP_1_GROUP_TYPE
  #   value: "GroupOfUniqueNamesType"
  # - name: AUTH_LDAP_1_USER_SEARCH
  #   value: "['OU=Users,DC=example,DC=com', 'SCOPE_SUBTREE', '(cn=%(user)s)']"
  # - name: AUTH_LDAP_1_START_TLS
  #   value: false
  # - name: AUTH_LDAP_1_REQUIRE_GROUP
  #   value: "cn=satellite-qe,ou=adhoc,ou=managedGroups,dc=example,dc=com"

  # Next name helps fetch Email addr and name from LDAP and save it in tower user.
  # - name: AUTH_LDAP_1_USER_ATTR_MAP
  #   value: '{"first_name": "displayName","last_name": "sn","email": "examplePrimaryMail"}'

  # Next name helps each sat-qe-infra group to become superuser in tower as soon as they login
  # - name: AUTH_LDAP_1_USER_FLAGS_BY_GROUP
    # value: "{u'is_superuser': ['cn=sat-qe-infra,ou=adhoc,ou=managedGroups,dc=example,dc=com']}"
  # This maps all users to satellite-qe org and makes sure they are not part of satlab-admin

# --- Logging ---
  - name: LOG_AGGREGATOR_HOST
    value: "https://192.168.57.1:8088/services/collector/event"

  - name: LOG_AGGREGATOR_PORT
    value: null

  - name: LOG_AGGREGATOR_TYPE
    value: "splunk"

  - name: LOG_AGGREGATOR_USERNAME
    value: ""

  # - name: LOG_AGGREGATOR_PASSWORD
  #   value: ""

  - name: LOG_AGGREGATOR_LOGGERS
    value: "['awx', 'activity_stream', 'job_events', 'system_tracking', 'broadcast_websocket']"

  - name: LOG_AGGREGATOR_INDIVIDUAL_FACTS
    value: false

  - name: LOG_AGGREGATOR_ENABLED
    value: false

  - name: LOG_AGGREGATOR_PROTOCOL
    value: "https"

  - name: LOG_AGGREGATOR_TCP_TIMEOUT
    value: "10"

  - name: LOG_AGGREGATOR_VERIFY_CERT
    value: false

  - name: LOG_AGGREGATOR_LEVEL
    value: "DEBUG"
    # DEBUG, WARNING, INFO

  - name: API_400_ERROR_LOG_FORMAT
    value: "status {status_code} received by user {user_name} attempting to access {url_path} from {remote_addr}"
...
